from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateCategoryRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None):  # noqa: E501
        """CreateCategoryRequest - a model defined in OpenAPI

        :param name: The name of this CreateCategoryRequest.  # noqa: E501
        :type name: str
        :param description: The description of this CreateCategoryRequest.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description'
        }

        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCategoryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_category_request of this CreateCategoryRequest.  # noqa: E501
        :rtype: CreateCategoryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CreateCategoryRequest.


        :return: The name of this CreateCategoryRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CreateCategoryRequest.


        :param name: The name of this CreateCategoryRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this CreateCategoryRequest.


        :return: The description of this CreateCategoryRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateCategoryRequest.


        :param description: The description of this CreateCategoryRequest.
        :type description: str
        """

        self._description = description
