from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.category import Category
from openapi_server import util

from openapi_server.models.category import Category  # noqa: E501

class PlayerLite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, discord_id=None, score=None, categories=None):  # noqa: E501
        """PlayerLite - a model defined in OpenAPI

        :param id: The id of this PlayerLite.  # noqa: E501
        :type id: str
        :param discord_id: The discord_id of this PlayerLite.  # noqa: E501
        :type discord_id: str
        :param score: The score of this PlayerLite.  # noqa: E501
        :type score: int
        :param categories: The categories of this PlayerLite.  # noqa: E501
        :type categories: List[Category]
        """
        self.openapi_types = {
            'id': str,
            'discord_id': str,
            'score': int,
            'categories': List[Category]
        }

        self.attribute_map = {
            'id': 'id',
            'discord_id': 'discord_id',
            'score': 'score',
            'categories': 'categories'
        }

        self._id = id
        self._discord_id = discord_id
        self._score = score
        self._categories = categories

    @classmethod
    def from_dict(cls, dikt) -> 'PlayerLite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlayerLite of this PlayerLite.  # noqa: E501
        :rtype: PlayerLite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this PlayerLite.


        :return: The id of this PlayerLite.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PlayerLite.


        :param id: The id of this PlayerLite.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def discord_id(self) -> str:
        """Gets the discord_id of this PlayerLite.


        :return: The discord_id of this PlayerLite.
        :rtype: str
        """
        return self._discord_id

    @discord_id.setter
    def discord_id(self, discord_id: str):
        """Sets the discord_id of this PlayerLite.


        :param discord_id: The discord_id of this PlayerLite.
        :type discord_id: str
        """
        if discord_id is None:
            raise ValueError("Invalid value for `discord_id`, must not be `None`")  # noqa: E501

        self._discord_id = discord_id

    @property
    def score(self) -> int:
        """Gets the score of this PlayerLite.


        :return: The score of this PlayerLite.
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score: int):
        """Sets the score of this PlayerLite.


        :param score: The score of this PlayerLite.
        :type score: int
        """
        if score is None:
            raise ValueError("Invalid value for `score`, must not be `None`")  # noqa: E501

        self._score = score

    @property
    def categories(self) -> List[Category]:
        """Gets the categories of this PlayerLite.


        :return: The categories of this PlayerLite.
        :rtype: List[Category]
        """
        return self._categories

    @categories.setter
    def categories(self, categories: List[Category]):
        """Sets the categories of this PlayerLite.


        :param categories: The categories of this PlayerLite.
        :type categories: List[Category]
        """
        if categories is None:
            raise ValueError("Invalid value for `categories`, must not be `None`")  # noqa: E501

        self._categories = categories
