from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.category import Category
from openapi_server import util

from openapi_server.models.category import Category  # noqa: E501

class Task(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, points=None, min_session=None, max_session=None, enabled=None, categories=None):  # noqa: E501
        """Task - a model defined in OpenAPI

        :param id: The id of this Task.  # noqa: E501
        :type id: str
        :param description: The description of this Task.  # noqa: E501
        :type description: str
        :param points: The points of this Task.  # noqa: E501
        :type points: int
        :param min_session: The min_session of this Task.  # noqa: E501
        :type min_session: int
        :param max_session: The max_session of this Task.  # noqa: E501
        :type max_session: int
        :param enabled: The enabled of this Task.  # noqa: E501
        :type enabled: bool
        :param categories: The categories of this Task.  # noqa: E501
        :type categories: List[Category]
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'points': int,
            'min_session': int,
            'max_session': int,
            'enabled': bool,
            'categories': List[Category]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'points': 'points',
            'min_session': 'min_session',
            'max_session': 'max_session',
            'enabled': 'enabled',
            'categories': 'categories'
        }

        self._id = id
        self._description = description
        self._points = points
        self._min_session = min_session
        self._max_session = max_session
        self._enabled = enabled
        self._categories = categories

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Task.


        :return: The id of this Task.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Task.


        :param id: The id of this Task.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Task.


        :return: The description of this Task.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Task.


        :param description: The description of this Task.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def points(self) -> int:
        """Gets the points of this Task.


        :return: The points of this Task.
        :rtype: int
        """
        return self._points

    @points.setter
    def points(self, points: int):
        """Sets the points of this Task.


        :param points: The points of this Task.
        :type points: int
        """
        if points is None:
            raise ValueError("Invalid value for `points`, must not be `None`")  # noqa: E501

        self._points = points

    @property
    def min_session(self) -> int:
        """Gets the min_session of this Task.


        :return: The min_session of this Task.
        :rtype: int
        """
        return self._min_session

    @min_session.setter
    def min_session(self, min_session: int):
        """Sets the min_session of this Task.


        :param min_session: The min_session of this Task.
        :type min_session: int
        """

        self._min_session = min_session

    @property
    def max_session(self) -> int:
        """Gets the max_session of this Task.


        :return: The max_session of this Task.
        :rtype: int
        """
        return self._max_session

    @max_session.setter
    def max_session(self, max_session: int):
        """Sets the max_session of this Task.


        :param max_session: The max_session of this Task.
        :type max_session: int
        """

        self._max_session = max_session

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this Task.


        :return: The enabled of this Task.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this Task.


        :param enabled: The enabled of this Task.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def categories(self) -> List[Category]:
        """Gets the categories of this Task.


        :return: The categories of this Task.
        :rtype: List[Category]
        """
        return self._categories

    @categories.setter
    def categories(self, categories: List[Category]):
        """Sets the categories of this Task.


        :param categories: The categories of this Task.
        :type categories: List[Category]
        """
        if categories is None:
            raise ValueError("Invalid value for `categories`, must not be `None`")  # noqa: E501

        self._categories = categories
