/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskRequest
     */
    points: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskRequest
     */
    minSession?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskRequest
     */
    maxSession?: number;
}

/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(value: object): value is CreateTaskRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'points': json['points'],
        'minSession': json['min_session'] == null ? undefined : json['min_session'],
        'maxSession': json['max_session'] == null ? undefined : json['max_session'],
    };
}

export function CreateTaskRequestToJSON(value?: CreateTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'points': value['points'],
        'min_session': value['minSession'],
        'max_session': value['maxSession'],
    };
}

