/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface GetCategories200Response
 */
export interface GetCategories200Response {
    /**
     * 
     * @type {Array<Category>}
     * @memberof GetCategories200Response
     */
    tasks: Array<Category>;
    /**
     * 
     * @type {number}
     * @memberof GetCategories200Response
     */
    count: number;
}

/**
 * Check if a given object implements the GetCategories200Response interface.
 */
export function instanceOfGetCategories200Response(value: object): value is GetCategories200Response {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetCategories200ResponseFromJSON(json: any): GetCategories200Response {
    return GetCategories200ResponseFromJSONTyped(json, false);
}

export function GetCategories200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCategories200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(CategoryFromJSON)),
        'count': json['count'],
    };
}

export function GetCategories200ResponseToJSON(value?: GetCategories200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(CategoryToJSON)),
        'count': value['count'],
    };
}

