/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerLite } from './PlayerLite';
import {
    PlayerLiteFromJSON,
    PlayerLiteFromJSONTyped,
    PlayerLiteToJSON,
} from './PlayerLite';

/**
 * 
 * @export
 * @interface GetPlayers200Response
 */
export interface GetPlayers200Response {
    /**
     * 
     * @type {Array<PlayerLite>}
     * @memberof GetPlayers200Response
     */
    players: Array<PlayerLite>;
    /**
     * 
     * @type {number}
     * @memberof GetPlayers200Response
     */
    count: number;
}

/**
 * Check if a given object implements the GetPlayers200Response interface.
 */
export function instanceOfGetPlayers200Response(value: object): value is GetPlayers200Response {
    if (!('players' in value) || value['players'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetPlayers200ResponseFromJSON(json: any): GetPlayers200Response {
    return GetPlayers200ResponseFromJSONTyped(json, false);
}

export function GetPlayers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(PlayerLiteFromJSON)),
        'count': json['count'],
    };
}

export function GetPlayers200ResponseToJSON(value?: GetPlayers200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'players': ((value['players'] as Array<any>).map(PlayerLiteToJSON)),
        'count': value['count'],
    };
}

