/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface GetTasks200Response
 */
export interface GetTasks200Response {
    /**
     * 
     * @type {Array<Task>}
     * @memberof GetTasks200Response
     */
    tasks: Array<Task>;
    /**
     * 
     * @type {number}
     * @memberof GetTasks200Response
     */
    count: number;
}

/**
 * Check if a given object implements the GetTasks200Response interface.
 */
export function instanceOfGetTasks200Response(value: object): value is GetTasks200Response {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetTasks200ResponseFromJSON(json: any): GetTasks200Response {
    return GetTasks200ResponseFromJSONTyped(json, false);
}

export function GetTasks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTasks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskFromJSON)),
        'count': json['count'],
    };
}

export function GetTasks200ResponseToJSON(value?: GetTasks200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskToJSON)),
        'count': value['count'],
    };
}

