/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface Player
 */
export interface Player {
    /**
     * 
     * @type {Array<Category>}
     * @memberof Player
     */
    tasks: Array<Category>;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    discordId: string;
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    score: number;
    /**
     * 
     * @type {Array<Category>}
     * @memberof Player
     */
    categories: Array<Category>;
}

/**
 * Check if a given object implements the Player interface.
 */
export function instanceOfPlayer(value: object): value is Player {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('discordId' in value) || value['discordId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function PlayerFromJSON(json: any): Player {
    return PlayerFromJSONTyped(json, false);
}

export function PlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Player {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(CategoryFromJSON)),
        'id': json['id'],
        'discordId': json['discord_id'],
        'score': json['score'],
        'categories': ((json['categories'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function PlayerToJSON(value?: Player | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(CategoryToJSON)),
        'id': value['id'],
        'discord_id': value['discordId'],
        'score': value['score'],
        'categories': ((value['categories'] as Array<any>).map(CategoryToJSON)),
    };
}

