/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    points: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    minSession?: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    maxSession?: number;
    /**
     * 
     * @type {Array<Category>}
     * @memberof Task
     */
    categories: Array<Category>;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'points': json['points'],
        'minSession': json['min_session'] == null ? undefined : json['min_session'],
        'maxSession': json['max_session'] == null ? undefined : json['max_session'],
        'categories': ((json['categories'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function TaskToJSON(value?: Task | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'points': value['points'],
        'min_session': value['minSession'],
        'max_session': value['maxSession'],
        'categories': ((value['categories'] as Array<any>).map(CategoryToJSON)),
    };
}

