/* tslint:disable */
/* eslint-disable */
/**
 * MC Taskmaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlayerRequest
 */
export interface UpdatePlayerRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdatePlayerRequest
     */
    score: number;
}

/**
 * Check if a given object implements the UpdatePlayerRequest interface.
 */
export function instanceOfUpdatePlayerRequest(value: object): value is UpdatePlayerRequest {
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function UpdatePlayerRequestFromJSON(json: any): UpdatePlayerRequest {
    return UpdatePlayerRequestFromJSONTyped(json, false);
}

export function UpdatePlayerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlayerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
    };
}

export function UpdatePlayerRequestToJSON(value?: UpdatePlayerRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'score': value['score'],
    };
}

